apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: dify-http-route
spec:
  parentRefs:
    - name: istio
      namespace: kube-system
      kind: Gateway
  hostnames:
    - "app.example.com"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
        - path:
            type: PathPrefix
            value: /api
        - path:
            type: PathPrefix
            value: /console/api
        - path:
            type: PathPrefix
            value: /v1
        - path:
            type: PathPrefix
            value: /files
        - path:
            type: PathPrefix
            value: /explore
      backendRefs:
        - name: dify-nginx
          port: 80
