#!/bin/bash
# Renders squid.conf.template → squid.conf and generates include files.
# Designed to run as an InitContainer in Kustomize deployment.

set -e

TEMPLATE_SRC=/template/squid.conf.template
CONF_DST=/etc/squid/squid.conf

# --- 1. Replace environment variables in the template ---
echo "[INIT] rendering squid.conf from template"
awk '{
    while(match($0, /\${[A-Za-z_][A-Za-z_0-9]*}/)) {
        var = substr($0, RSTART+2, RLENGTH-3)
        val = ENVIRON[var]
        $0 = substr($0, 1, RSTART-1) val substr($0, RSTART+RLENGTH)
    }
    print
}' "$TEMPLATE_SRC" > "$CONF_DST"

# --- 2. Generate allow private conf ---
ALLOW_PRIVATE_CONF=/etc/squid/dify_allow_private.conf
write_optional_private_allowlist() {
    local env_name="$1"
    local acl_name="$2"
    local acl_type="$3"
    local raw_values="${!env_name:-}"

    raw_values="${raw_values//,/ }"

    if [ -z "${raw_values//[[:space:]]/}" ]; then
        return
    fi

    printf 'acl %s %s' "$acl_name" "$acl_type" >> "$ALLOW_PRIVATE_CONF"
    for value in $raw_values; do
        printf ' %s' "$value" >> "$ALLOW_PRIVATE_CONF"
    done
    printf '\nhttp_access allow client_localnet %s\n' "$acl_name" >> "$ALLOW_PRIVATE_CONF"
}

{
    echo "# Generated by init.sh."
    echo "# Allows selected private targets before the default private-network deny rule."
} > "$ALLOW_PRIVATE_CONF"
write_optional_private_allowlist "SSRF_PROXY_ALLOW_PRIVATE_IPS" "dify_allowed_private_networks" "dst"
write_optional_private_allowlist "SSRF_PROXY_ALLOW_PRIVATE_DOMAINS" "dify_allowed_private_domains" "dstdomain"

# --- 3. Generate sandbox proxy conf ---
SANDBOX_PROXY_CONF=/etc/squid/dify_sandbox_proxy.conf
{
    echo "# Generated by init.sh."
    echo "# Enables the middleware-only sandbox host bridge when configured."
} > "$SANDBOX_PROXY_CONF"

if [ -n "${SSRF_SANDBOX_PROXY_PORT:-}" ]; then
    sandbox_proxy_host="${SSRF_SANDBOX_PROXY_HOST:-dify-sandbox}"
    sandbox_proxy_target_port="${SANDBOX_PORT:-8194}"

    {
        printf 'http_port %s accel vhost\n' "$SSRF_SANDBOX_PROXY_PORT"
        printf 'cache_peer %s parent %s 0 no-query originserver name=dify_sandbox\n' \
            "$sandbox_proxy_host" \
            "$sandbox_proxy_target_port"
        printf 'acl dify_sandbox_proxy_port localport %s\n' "$SSRF_SANDBOX_PROXY_PORT"
        printf 'http_access allow dify_sandbox_proxy_port\n'
    } >> "$SANDBOX_PROXY_CONF"
fi

echo "[INIT] config generation complete"
