resources:
  - deployment.yaml
  - service.yaml
labels:
  - pairs:
      app.kubernetes.io/name: dify-ssrf
    includeSelectors: true
configMapGenerator:
  - name: ssrf-proxy-template
    files:
      - squid.conf.template=squid.conf.template
  - name: ssrf-proxy-entrypoint
    files:
      - docker-entrypoint-mount.sh=docker-entrypoint-mount.sh
      - init.sh=init.sh
generatorOptions:
  disableNameSuffixHash: true
