---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dify-sandbox
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: dify-sandbox
          image: langgenius/dify-sandbox:0.2.12
          env:
            - name: API_KEY
              valueFrom:
                configMapKeyRef:
                  name: dify-shared-config
                  key: SANDBOX_API_KEY
            - name: GIN_MODE
              valueFrom:
                configMapKeyRef:
                  name: dify-shared-config
                  key: SANDBOX_GIN_MODE
            - name: WORKER_TIMEOUT
              valueFrom:
                configMapKeyRef:
                  name: dify-shared-config
                  key: SANDBOX_WORKER_TIMEOUT
            - name: ENABLE_NETWORK
              valueFrom:
                configMapKeyRef:
                  name: dify-shared-config
                  key: SANDBOX_ENABLE_NETWORK
            - name: HTTP_PROXY
              valueFrom:
                configMapKeyRef:
                  name: dify-shared-config
                  key: SANDBOX_HTTP_PROXY
            - name: HTTPS_PROXY
              valueFrom:
                configMapKeyRef:
                  name: dify-shared-config
                  key: SANDBOX_HTTPS_PROXY
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 1Gi
          livenessProbe:
            exec:
              command:
                - "curl"
                - "-f"
                - "http://localhost:8194/health"
          ports:
            - containerPort: 8194
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: dify-sandbox-dependencies
              mountPath: /dependencies
            - name: dify-sandbox-config
              mountPath: /conf
      volumes:
        - name: dify-sandbox-dependencies
          configMap:
            name: dify-sandbox-dependencies
        - name: dify-sandbox-config
          configMap:
            name: dify-sandbox-config
