resources:
  - shared/
  - api/
  - nginx/
  - plugin/
  - sandbox/
  - web/
  - worker/
  - worker-beta/
  - weaviate/
  - postgres/
  - ssrf/
  - redis/

labels:
  - pairs:
      app.kubernetes.io/managed-by: kustomize
    includeSelectors: true
